### ISSUE TITLE
Charset problem

### ISSUE THREAD

**Issue by dzNavitski** [code-orchestra/colt-ui#2] opened 2014-04-06 11:18 UTC
In live mode doesn't display correctly cyrillic text.

**Comment by makc** [comment] 2014-04-06 18:29
is your html utf8 or win1251 or ...? do you have &lt;meta ...&gt; tag? if so, could you paste it here?

**Comment by dzNavitski** [comment] 2014-04-07 05:53
meta charset="utf-8"

**Comment by dzNavitski** [comment] 2014-04-07 05:58
when i look http headers i find that there is no chraset

**Comment by makc** [comment] 2014-04-07 11:49
there is no http header, indeed, because there is no encoding detection in colt (beyond the absence/presence of [bom](http://en.wikipedia.org/wiki/Byte_order_mark)). however, I can't reproduce any problem :(
![screen shot 2014-04-07 at 1 45 03 pm](https://cloud.githubusercontent.com/assets/242577/2630499/a83d1cf6-be4a-11e3-9bef-f929a0d40005.png)
could you please attach some example and/or give more hints (os, browser)?

**Comment by dzNavitski** [comment] 2014-04-07 20:03
I have windows 8.1. Problem take a place in all browsers (chrome, ie, firefox).
I attach screenshot. 
![colt](https://cloud.githubusercontent.com/assets/4883032/2636285/9e63f1b0-be8f-11e3-8c86-227a611cbbac.jpg)

**Comment by makc** [comment] 2014-04-08 14:51
Should be fixed with commit 4c137bf686f7c2018cf461ba618c0a9114b8d007 - you can either wait for update or add these VM params manually to your COLT\app\services.js in case you want to test this immediately.

**Comment by dzNavitski** [comment] 2014-04-08 19:45
Thanks, work great

**Comment by makc** [comment] 2014-04-08 22:27
:+1:

**Closed as completed by makc** 2014-04-08 22:27 UTC
